# Generated by Django 6.0.7 on 2026-07-28 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.IntegerField(choices=[(30, '30 min'), (60, '1 h'), (90, '1 h 30 min'), (120, '2 h'), (150, '2 h 30 min'), (180, '3 h'), (210, '3 h 30 min'), (240, '4 h')], default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('reason', models.CharField(choices=[('routine', 'Routine Check-up'), ('vaccine', 'Vaccination'), ('illness', 'Illness / Sickness'), ('emergency', 'Emergency'), ('surgery', 'Surgery'), ('followup', 'Follow-up'), ('other', 'Other')], default='routine', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.animal')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
