# Generated by Django 6.0.7 on 2026-08-03 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('complaint', models.TextField()),
                ('notes', models.TextField()),
                ('risk_level', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.animal')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_media', models.FileField(blank=True, null=True, upload_to='consultations/media/')),
                ('ai_transcription_consultation', models.TextField(blank=True, null=True)),
                ('ai_summary_consultation', models.TextField(blank=True, null=True)),
                ('exam_pdf', models.FileField(blank=True, null=True, upload_to='consultations/exams/')),
                ('ai_exam_ocr_text', models.TextField(blank=True, null=True)),
                ('ai_exam_interpretation', models.JSONField(blank=True, null=True)),
                ('clinical_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clients.animal')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='clients.appointment')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'VET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='clients.triage')),
            ],
        ),
    ]
